### ISSUE TITLE
ERROR (7644): An error occured during session read

### ISSUE THREAD

**Issue by Marcoant007** [Marcoant007/baileys-store#1]
Error message: 
```
   err: {
      "type": "NotFoundError",
      "message": "No Session found",
      "stack":
          NotFoundError: No Session found
              at C:\Users\Dell\Desktop\Projetos\whatsapp-api\node_modules\@prisma\client\runtime\library.js:162:6027
              at C:\Users\Dell\Desktop\Projetos\whatsapp-api\node_modules\@prisma\client\runtime\library.js:162:5966
              at read (C:\Users\Dell\Desktop\Projetos\whatsapp-api\node_modules\mrx-baileys-store\dist\session.js:32:30)
              at C:\Users\Dell\Desktop\Projetos\whatsapp-api\node_modules\mrx-baileys-store\dist\session.js:67:37
              at async Promise.all (index 0)
              at Object.get (C:\Users\Dell\Desktop\Projetos\whatsapp-api\node_modules\mrx-baileys-store\dist\session.js:66:21)
              at Object.get (C:\Users\Dell\Desktop\Projetos\whatsapp-api\node_modules\@whiskeysockets\baileys\lib\Utils\auth-utils.js:43:33)
              at Object.processSenderKeyDistributionMessage (C:\Users\Dell\Desktop\Projetos\whatsapp-api\node_modules\@whiskeysockets\baileys\lib\Signal\libsignal.js:42:49)
              at decrypt (C:\Users\Dell\Desktop\Projetos\whatsapp-api\node_modules\@whiskeysockets\baileys\lib\Utils\decode-wa-message.js:133:29)
              at C:\Users\Dell\Desktop\Projetos\whatsapp-api\node_modules\@whiskeysockets\baileys\lib\Socket\messages-recv.js:539:17
      "code": "P2025",
      "clientVersion": "4.15.0",
      "name": "NotFoundError"
```

**Comment by Marcoant007** [comment]
Bug fixed in PR below
PR -> https://github.com/Marcoant007/mrx-baileys-store/pull/2

**Comment by Marcoant007** [comment]
Bug fixed in PR below
PR -> https://github.com/Marcoant007/mrx-baileys-store/pull/2 #2
